fw_link_data = {
  1: {'model': 'bf3', 'link': 'https://downloaders.azurewebsites.net/downloaders/bluefield3_fw_downloader/downloader.html'}, 
  2: {'model': 'bf2', 'link': 'https://downloaders.azurewebsites.net/downloaders/bluefield2_fw_downloader/downloader.html'},
  3: {'model': 'cx7', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx7_downloader/downloader.html'},
  4: {'model': 'cx6de', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx6de_downloader/downloader.html'},
  5: {'model': 'cx6lx', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx6lx_downloader/downloader.html'},
  6: {'model': 'cx6dx', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx6dx_downloader/downloader2.html'},
  7: {'model': 'cx6en', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx6en_downloader/downloader1.html'},
  8: {'model': 'cx6ib', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx6ib_downloader/downloader1.html'},
  9: {'model': 'cx5en', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx5en_downloader/downloader2.html'},
  10: {'model': 'cx5ib', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx5ib_downloader/downloader3.html'},
  11: {'model': 'cx4lx', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx4lxen_downloader/downloader3.html'},
  12: {'model': 'cx4en', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx4en_downloader/downloader3.html'},
  13: {'model': 'cx4ib', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx4ib_downloader/downloader4.html'},
  14: {'model': 'cx3proen', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx3proen_downloader/downloader2.html'},
  15: {'model': 'cx3proib', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx3proib_downloader/downloader2.html'},
  16: {'model': 'cx3en', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx3en_downloader/downloader2.html'},
  17: {'model': 'cx3ib', 'link': 'https://downloaders.azurewebsites.net/downloaders/connectx3ib_downloader/downloader2.html'},
  18: {'model': 'quantum2', 'link': 'https://downloaders.azurewebsites.net/downloaders/quantum2_downloader/downloader.html'},
  19: {'model': 'quantum', 'link': 'https://downloaders.azurewebsites.net/downloaders/quantum_downloader/downloader1.html'},
  20: {'model': 'switchib2', 'link': 'https://downloaders.azurewebsites.net/downloaders/switchib2_downloader/downloader1.html'},
  21: {'model': 'switchib', 'link': 'https://downloaders.azurewebsites.net/downloaders/switchib_downloader/downloader1.html'},
}
